version: 2
workflows:
  version: 2
  MyPipe:
    jobs:
      - build
      - build docker image

jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - persist_to_workspace: {root: /go/src/github.com/kassybas/circle-test, paths: [.]}
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build docker image:
    docker:
      - image: docker:dind
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - setup_remote_docker
      - run: docker build -t trivago/trash:bcircle .
      - run: docker images
