version: 2
workflows:
  version: 2
  MyPipe:
    jobs:
      - build
      - build docker image
          requires:
            - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: go build .
      - persist_to_workspace:
          root: ./
          path:
            - circle-test
  build docker image:
    docker:
      - image: docker:dind
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /go/src/github.com/kassybas/circle-test
      - run: docker build -t trivago/trash:bcircle .
      - run: docker images
