version: 2
workflows:
  version: 2
  MyPipe:
    jobs:
      - build
      - deploy
jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run: echo "I build now"
  deploy:
    docker:
      - image: ubuntu
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run: echo "I die now"
