version: 2
workflows:
  version: 2
  MyPipe:
    jobs:
      - build
      - deploy:
          requires: [build]
      - notify:
          requires: [deploy]
jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run: echo "I build now"
      - run: exit 1
  deploy:
    docker:
      - image: ubuntu
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run: echo "I die now"
  notify:
    docker:
      - image: ubuntu
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run:
         command: echo "i notify now"
         when: always
