version: 2
workflows:
  version: 2
  MyPipe:
    jobs:
      - build
      - deploy:
          requires:
            - build
jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run: make build
  deploy:
    docker:
      - image: ubuntu
    working_directory: /go/src/github.com/kassybas/circle-test
    steps:
      - checkout
      - run: make deploy
